---@meta
--- Many functions require a handle as an argument or return a handle.
--- The handle is a custom data type called =="light_userdata"==.
--- The handle is a unique identifier that refers to a grandMA3 object, for instance, a specific sequence, cue, preset, or fixture.
--- The object the handle refers to has some properties. Some can be changed, and some are read-only. The object might also have child objects. The object always has Name, Class, and Path information.
--- The path is the same as an address that identifies where the object exists in the structure of the showfile.
---@class MAHandle
---@field Name string
---@field Class string
---@field Path string

---@alias FaderToken
---| "FaderMaster"
---| "FaderX"
---| "FaderXA"
---| "FaderXB"
---| "FaderTemp"
---| "FaderRate"
---| "FaderSpeed"
---| "FaderHighlight"
---| "FaderLowlight"
---| "FaderSolo"
---| "FaderTime"

---@class FaderOptions
---@field token FaderToken
---@field index? integer

---@class SetFaderOptions
---@field value? number
---@field token? FaderToken
---@field faderEnabled? boolean
